### ISSUE TITLE
历史记录按时间倒序给出

### ISSUE THREAD

**Issue by Altermoe** [kongying-tavern/genshin-map-cloud#17]
当前历史记录接口返回的历史记录是按时间正序排列的，希望改为时间倒序，以便打点员就最新的历史记录进行对比

**Comment by Altermoe** [comment]
当前历史记录接口返回的历史记录是按时间正序排列的，希望改为时间倒序，以便打点员就最新的历史记录进行对比

**Comment by boxsnake** [comment]
参数
`sort: ["updateTime+" | "updateTime-"]`
